= Produktdokumentation

In diesem Ordner befindet sich die Dokumentation zum Produkt. Dazu gehört:

- Softwaredokumentation (SAD)
- Hardware-Dokumentation
- Testdokumentation
- Programmierkonventionen

== Softwaredokumentation
Der Aufbau und die Entwicklung der Software sind im SAD dokumentiert. Dort finden Sie informationen zu 
- Randbedingungen
- Kontextabgrenzung
- Lösungsstrategie
- Bausteinsicht
- Laufzeitsicht
- Verteilungssicht
- Querschnittliche Konzepte
- Architekturentscheidungen
- Qualitätsanforderungen
- Risiken und technische Schulden
- Glossar

== Hardwaredokumentation
Die Hardwaredokumentation befindet sich im README.md des Hauptprojekts (ip12-23vt_wegwerfgesellschaft/README.md). Dort finden Sie:

- einen Bauplan des Kastens
- eine Liste der verbauten Komponenten
- einen Schaltplan der Elektronik


== Testdokumentation
Die Testdokumentation finden sie im Ordner *testing*. Dort finden Sie:
- Usability-Tests
- Qualitätsprüfungen
- Leistungstests
- Hardware-Tests
- Funktionalitätstests


== Programmierkonventionen (Coding-Conventions)
Die Coding Conventions liegen sowohl als .docx als auch als .adoc file vor. Die Coding-Conventions definieren strukturelle und syntaktische Richtlinien die von den Entwicklern eingehalten werden müssen und zu einer hohen Code-Qualität führt.
